### ISSUE TITLE
AI and Blockchain Fusion

### ISSUE THREAD

**Issue by Vanova** [EtherSingapore/talks#10]
## Language 
 English / Mandarin  / Other

     English
 
## Abstract
  - Blockchain revolution
  - AI revolution
  - How to fuse AI and Blockchain
  - Examples

## Preferences 

 Accept Livestream /
 No livestream, accept video recording / 
 Prohibit video recording / 
 Prohibit photographing / 
 
     Accept Livestream
 
## Duration 
~ XX mins

      50 mins

## Contact info 

Email:   [ivan@kukanov.com](ivan@kukanov.com)
Personal page: [www.kukanov.com](http://www.kukanov.com)
     

## Other Preferences  (Optional)

**Comment by kennethhutw** [comment]
Slides :  https://www.slideshare.net/KukanovIvan/ai-and-blockchain-fusion
Video : https://youtu.be/LWPDsBs-u3Y
