### ISSUE TITLE
Ethereum, Bitcoin APIs & how to use them

### ISSUE THREAD

**Issue by dilumn** [EtherSingapore/talks#2]
## Language

English

## Abstract 

Ethereum & Bitcoin have their own RPC APIs which we can use to connect to those blockchains. Using those APIs we can use all the things that GUI wallets do. So this talk is about how to connect with these APIs & use them programmatically in your server side application which gives you more robust access to the blockchains.

## Preferences

Accept Livestream

## Duration

~ 25 mins

## Contact info

Email: dilumnavanjana@gmail.com

## Slides

https://www.slideshare.net/DilumNavanjana/connect-to-bitcoin-ethereum-networks-rpc-apis

## Video
https://youtu.be/jeaX6Y5jnAc

**Comment by kennethhutw** [comment]
## Video
https://youtu.be/jeaX6Y5jnAc
## Slides
https://www.slideshare.net/DilumNavanjana/connect-to-bitcoin-ethereum-networks-rpc-apis

**Comment by kennethhutw** [comment]
## Video
https://youtu.be/jeaX6Y5jnAc
